# Generated by Django 5.0.1 on 2026-01-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly version of title', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('excerpt', models.TextField(help_text='Short summary for the homepage card')),
                ('content', models.TextField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated minutes to read')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
